### ISSUE TITLE
Serious Problem of Uploading CSV File to Create Gazette 

### ISSUE THREAD

**Issue by ghost** [RecastAI/Recast.AI#43]
**No matter how many synonyms in the CSV file**, only the first ~200 synonyms are created in the gazette. It would be WAY TOO tedious to enter thousands of synonyms one by one!

**Comment by dbousque** [comment]
Hi @AlbertZLiang , it is not very obvious because there is no feedback given in the frontend, but you should wait until the HTTP request is completely finished before leaving the page :) I think there is a toast when the request is finished, but otherwise you can always check out the 'Network' tab of your browser dev tools. Let me know if that was it.

**Comment by dbousque** [comment]
Can you give me your nickname on Recast, as well as the name of your bot and the name of the gazette please ? Could you also send me your CSV file ? I want to investigate what might happen.

**Comment by AlbertZLiang** [comment]
Nickname on Recast: albertliang
Name of bot: sap
Name of gazette: TCODE
CSV File: https://drive.google.com/open?id=1HoV5KGGqMj38tcfvUH5dmBNU__L8vciJ

**Comment by dbousque** [comment]
So, after investigation, it turns out that the issue is the one I mentioned, namely that the HTTP request takes too long. What you can do to go around this issue is to upload your gazette using the API, 100 synonyms (a gazette is basically a list of synonyms) at a time. Take a look here : https://recast.ai/docs/api-reference/#bulk-creating-synonyms

**Comment by AlbertZLiang** [comment]
Using API works. Thank you~
