### ISSUE TITLE
Recast  "Add Quick reply" positioning with slack

### ISSUE THREAD

**Issue by archanarai2211** [RecastAI/Recast.AI#55]
Hi,

I am integrating recast with slack and what I notice is, when you add quick reply as a message the recast UI can take only 3 buttons in one row, which is alright as there is only space for three, the fourth button goes down.
But when this is integrated with slack, even though slack has lot of space for the fourth button it still goes to the second row, which makes it look unprofessional.
Attaching the screenshots.

Thanks,
![recastui](https://user-images.githubusercontent.com/8438421/42306379-5e212130-804c-11e8-89b6-d132ecf072b7.PNG)
![slackui](https://user-images.githubusercontent.com/8438421/42306386-65d2e454-804c-11e8-8c31-d4c38134bdd2.PNG)

Archana

**Comment by dbousque** [comment]
Hi @archanarai2211 , Slack displays them this way because it thinks it's the best way to display them. We don't send any information regarding the position of your quick replies to Slack. In fact, we don't even have this information, because it depends on your device, the rows will be different on mobile, it's just a bunch of CSS laying out stuff so it spreads out :)
