### ISSUE TITLE
[Help]NodeJS api call "Redirect to 'skill'  and  Wait for user input"

### ISSUE THREAD

**Issue by LarsVlyminckx** [RecastAI/Recast.AI#66]
Example:
User gives a date so chatbot needs to check if it exists in SQL database.
           If found tell user and go to skill (for example) "confirm date".
           If not found tell user.
Is it possible to send your (bot) message and then go to the specific skill.

```
if (result.length > 0) {
            res.json({
                replies: [
                    {
                        type: 'text',
                        content: `Date: ${begindate.toLocaleDateString()}`,
                    },
                    {
                        "type": "buttons",
                        "content": {
                            "title": "Is this your date?",
                            "buttons": [
                                {
                                    "title": "Yes",
                                    "type": "BUTTON_TYPE",
                                    "value": "Yes"
                                },
                                {
                                    "title": "No",
                                    "type": "BUTTON_TYPE",
                                    "value": "No"
                                }
                            ]
                        }
                    }
                ],
            })
        }
```
-> Now I want to say go to this skill

**Comment by ftriquet** [comment]
Hello,
Do you want the bot to execute the next skill just now or after the user's next message?

**Comment by LarsVlyminckx** [comment]
After user’s next message

**Comment by ftriquet** [comment]
Ok so what you probably want to do is to add a goto action after the webhook action, with "wait for user input". And in the skill you want to execute when the next message comes, add a requirement expecting intent yes or no.
You'll then be able to use the requirement value to do different things depending on the user's response. Here is an example (the webhook call is replaced by a message but the idea is the same):  https://recast.ai/ftriquet/wait-for-input-example/skills.
You can see the behavior by saying 
- Hello
- Tomorrow
- Click a button or say yes/no 
Note that since the `validate-date` skill has no trigger, it will not be executed if the users says something else than yes or no.
If you want the skill to be executed in 100% of the case, it's also possible.
