### ISSUE TITLE
capture the entire log of a conversation.

### ISSUE THREAD

**Issue by yimialejoh** [RecastAI/Recast.AI#85]
I want to get all the log of the conversation to send it by mail to the user, I currently use botbuilder and I capture the logs in the following way (but I can not capture the message that the bot sends):

![image](https://user-images.githubusercontent.com/38698937/46084203-ba3b2d00-c168-11e8-845c-43aae69bc8bb.png)

Any idea to capture the entire log of the conversation?

**Comment by dbousque** [comment]
If you use the bot-connector, you can use this endpoint to retrieve the messages sent in a conversation : https://recast.ai/docs/api-reference/#showing-a-conversation. Otherwise, you are calling `/dialog` directly, and so you get the responses directly as well. Even if you use the bot-connector, you can tell the bot-connector not to send your messages to your bot-builder but to your backend, and call `/dialog` directly in your backend, so that all messages transition through your server before being sent to the bot-builder.
